# Generated by Django 3.1.6 on 2021-02-26 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210226_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
    ]
