# Generated by Django 3.1.6 on 2021-02-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210226_0353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='blogcomment',
            old_name='comment',
            new_name='blog_comment',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='comment_created_date'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='post_created_date'),
        ),
    ]
