# Generated by Django 3.1.6 on 2021-02-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='name',
        ),
    ]
